baseURL = "https://mrjoema.github.io/tech-blog/"
languageCode = "en-us"
title = "Joe Ma's Tech Blog"
theme = "LoveIt"
[pagination]
  pagerSize = 10
enableRobotsTXT = true
hasCJKLanguage = false

# Permalinks (optional)
[permalinks]
  posts = "/:year/:month/:slug/"

# Markup & code highlight
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true  # allow raw HTML (for Mermaid scripts if you embed)

# Menus
[menu]
  [[menu.main]]
    name = "Posts"
    url  = "/posts/"
    weight = 10
  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 20

# Theme params
[params]
  version = "1.0"
  description = "Systems, infra, ML, SDUI notes"
  defaultTheme = "auto"   # light/dark
  disableThemeToggle = false
  
  # Header config
  [params.header]
    # desktop header mode
    desktopMode = "fixed"
    # mobile header mode
    mobileMode = "auto"
    # Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "Joe Ma's Tech Blog"
      # whether to add subtitle
      typeit = false

  # Author box (optional)
  [params.author]
    name = "Joe Ma"
    email = "joema.dev@gamil.com"

  # Site features
  [params.page]
    enableToc = true
    enableShare = false
    enableReadingTime = true
    enableWordCount = true
    enableComment = false
    showCodeCopyButtons = true

  # Search configuration
  [params.search]
    enable = true
    type = "lunr"
    contentLength = 4000
    placeholder = "Search..."
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false

  # KaTeX math
  [params.math]
    enable = true
    use = "katex"

  # Mermaid diagrams
  [params.diagram]
    enable = true
    library = "mermaid"

  # Analytics config
  [params.analytics]
    # Google Analytics
    [params.analytics.google]
      # Google Analytics ID will be injected from environment variable at build time
      id = "${HUGO_GOOGLE_ANALYTICS_ID}"
      # whether to respect the browser's "do not track" setting
      respectDoNotTrack = false

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Output formats needed for search index, RSS, etc.
[outputs]
  home = ["HTML", "RSS", "JSON"]
  