baseURL = "https://mrjoema.github.io/"
languageCode = "en-us"
title = "Joe Ma Dev Tech Blog"
theme = "LoveIt"

[pagination]
  pagerSize = 10

# Disable problematic features temporarily
[params]
  version = "1.0"
  description = "Systems, infra, ML, SDUI notes"
  defaultTheme = "light"
  
  [params.search]
    enable = true
    type = "fuse"
    
  [params.code]
    [params.code.render]
      goat = false
      mermaid = false

[menu]
  [[menu.main]]
    name = "Posts"
    url  = "/posts/"
    weight = 10
  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 20
  [[menu.main]]
    name = "Search"
    url  = "/search/"
    weight = 30